import { Category, MenuItem } from '../types';

export const INITIAL_MENU: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Arancini',
    description: 'Crispy risotto balls infused with black truffle and mozzarella.',
    price: 12,
    category: Category.STARTERS,
    image: 'https://picsum.photos/400/300?random=1',
    available: true,
    stock: 25,
  },
  {
    id: '2',
    name: 'Wagyu Beef Sliders',
    description: 'Mini brioche buns, aged cheddar, caramelized onions.',
    price: 18,
    category: Category.STARTERS,
    image: 'https://picsum.photos/400/300?random=2',
    available: true,
    stock: 15,
  },
  {
    id: '3',
    name: 'Pan-Seared Scallops',
    description: 'Served with cauliflower purée and crispy pancetta.',
    price: 22,
    category: Category.STARTERS,
    image: 'https://picsum.photos/400/300?random=3',
    available: false,
    stock: 0,
  },
  {
    id: '4',
    name: 'Lobster Linguine',
    description: 'Fresh pasta, cherry tomatoes, chili, garlic, and half a lobster.',
    price: 38,
    category: Category.MAINS,
    image: 'https://picsum.photos/400/300?random=4',
    available: true,
    stock: 8,
  },
  {
    id: '5',
    name: 'Herb-Crusted Lamb Rack',
    description: 'Served with fondant potatoes and red wine reduction.',
    price: 42,
    category: Category.MAINS,
    image: 'https://picsum.photos/400/300?random=5',
    available: true,
    stock: 12,
  },
  {
    id: '6',
    name: 'Wild Mushroom Risotto',
    description: 'Arborio rice, porcini mushrooms, parmesan crisp (V).',
    price: 28,
    category: Category.MAINS,
    image: 'https://picsum.photos/400/300?random=6',
    available: true,
    stock: 20,
  },
  {
    id: '7',
    name: 'Signature Old Fashioned',
    description: 'Bourbon, smoked maple syrup, angostura bitters.',
    price: 16,
    category: Category.DRINKS,
    image: 'https://picsum.photos/400/300?random=7',
    available: true,
    stock: 50,
  },
  {
    id: '8',
    name: 'Yuzu & Basil Smash',
    description: 'Gin, fresh yuzu juice, basil leaves, soda.',
    price: 15,
    category: Category.DRINKS,
    image: 'https://picsum.photos/400/300?random=8',
    available: true,
    stock: 50,
  },
  {
    id: '9',
    name: 'Chef\'s Surf & Turf',
    description: 'Fillet Mignon paired with grilled tiger prawns.',
    price: 55,
    category: Category.SPECIALS,
    image: 'https://picsum.photos/400/300?random=9',
    available: true,
    stock: 5,
  },
];
